name: ez_meditation_app
description: A new Flutter project.
publish_to: none

version: 1.0.1+01000101

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  animated_text_kit: ^4.2.1
  animations: ^2.0.0
  cached_network_image: ^3.0.0
  circular_countdown_timer: ^0.2.0
  cloud_firestore: ^4.3.1
  confetti: ^0.7.0
  duration: ^3.0.6
  duration_picker: ^1.0.0
  equatable: ^2.0.0
  firebase_auth: ^4.2.5
  firebase_core: ^2.4.1
  firebase_crashlytics: ^3.0.10
  firebase_analytics: ^10.1.0
  firebase_dynamic_links: ^5.0.11
  firebase_messaging: ^14.2.1
  firebase_storage: ^11.0.10
  flutter_cache_manager: ^3.1.1
  flutter_launcher_icons: ^0.11.0
  flutter_sfsymbols: ^2.0.0
  flutter_spinkit: ^5.0.0
  flutter_statusbarcolor_ns: ^0.5.0
  focused_menu: ^1.0.5
  freezed_annotation: ^2.2.0
  get: ^4.1.4
  get_it: ^7.1.3
  get_storage: ^2.0.2
  getwidget: ^3.0.1
  google_sign_in: ^5.0.4
  hive: ^2.0.4
  hive_flutter: ^1.0.0
  hive_generator: ^2.0.0
  image: ^3.0.2
  image_cropper: ^3.0.1
  image_picker: ^0.8.0+3
  just_audio: ^0.9.31
  logger: ^1.0.0
  package_info: ^2.0.0
  path_provider: ^2.0.1
  pedantic: ^1.11.0
  rate_my_app: ^1.1.0+1
  rxdart: ^0.27.0
  share: ^2.0.4
  sign_in_with_apple: ^4.3.0
  stacked: ^3.1.0+2
  stacked_services: ^0.9.9
  table_calendar: ^3.0.0
  timer_count_down: ^2.1.0+1
  url_launcher: ^6.0.3
  wakelock: ^0.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.4
  flutter_native_splash: ^2.2.16
  freezed: ^2.3.2
  json_serializable: ^6.5.4

#flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: true
  ios: true
  image_path_ios: "assets/ic_launcher_ios.png"
  image_path: "assets/ic_black_stone.png"
  adaptive_icon_background: #2A2A2A

#flutter pub run flutter_native_splash:create
flutter_native_splash:
  color: "#ffffff"
  image: assets/ic_splash.png

flutter:
  uses-material-design: true
  fonts:
    - family: sficonsets
      fonts:
        - asset: packages/flutter_sfsymbols/fonts/sficonsets.ttf
  assets:
    - assets/
    - assets/bell.mp3

flutter_intl:
  enabled: true
